baseURL: "https://example.com"
languageCode: "en-us"
title: "Steel Wagstaff"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 50
social:
  twitter: "https://twitter.com/steelwagstaff"
  github: "https://github.com/steelwagstaff"
  instagram: "#"
  linkedin: "https://www.linkedin.com/in/steel-wagstaff/"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors